print ("The cat said, \"" + "meow meow meow meow" + "\"")
print ("\n\takfjoahefwoiehfiohwegfhswj\neghhegheighiwahihjnisgajshfkdahfjkahefjke")
print ("This is a famous math formula: \"" + "E = mc**2" + "\"")
print ("\"" + "Where are the knives?" + "\" she asked.")
print ("Celeste said, \"" + "I like actually like peanut butter!" + "\"")
print ("Kills: 1\nDeaths: 5\nAssists: 3")
print ("According to my experimentations, \"" + "There is always an extra quote mark on the right." + "\"")
print ("\t1\n+\t1\n_________\n\t2")
print ("\"" + "Why are we running when I can be doing that soummersault thing?" + "\" said Taka as he ran towards the turret.")
print ("One of Petal's quotes is \"" + "Sparkle-pow!" + "\"")
print ("Petal's hidden quote is \"" + "Now tell me the truth: Do my pets look like onions?" + "\"")
print ("Sometimes Vox says, \"" + "Did you know that if you yell into a minion's mouth, it echoes?" + "\"")
for x in "ao4ery8gqe5rail":
    print(x + "\n" + x + "\t" + x + "\n")
print ("The Mini Pekka says, \"" + "Pancakes." + "\"")
